//! Chrome Fallback Broker — the **Fallback** stage of Observe → Act → Verify →
//! Fallback.
//!
//! RB-first: the lean HTTP pipeline stays the default. Only when RB's own
//! extraction looks insufficient does the broker escalate ONE page load to the
//! system's headless Chrome — and even then the rendered DOM is re-distilled
//! through the same token-lean pipeline, so the LLM never sees a raw DOM or a
//! screenshot.
//!
//! The decision is pure and explainable: every escalation carries a
//! [`FallbackReason`] that lands in the planner view and the operation log,
//! instead of a silent mode switch.

use crate::Distilled;
use crate::render;

/// Why the broker decided RB-only extraction is not enough for this page.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FallbackReason {
    /// An anti-bot / captcha interstitial was detected. A real browser may pass
    /// a JS challenge; an actual captcha will still need a human or a higher
    /// tier — the reason label tells the planner which bet it is making.
    Challenge,
    /// The page looks like an unrendered client-side app (framework markers,
    /// script-heavy shell, canvas/shadow-DOM UI) and distilled almost nothing.
    JsApp,
    /// Action extraction found nothing operable on a script-heavy page — the
    /// links/forms are most likely generated by JavaScript at runtime.
    NoActions,
    /// The caller forced rendering (`JsMode::Always`).
    Forced,
}

impl FallbackReason {
    /// Stable lowercase label for logs and the planner view.
    pub fn label(self) -> &'static str {
        match self {
            FallbackReason::Challenge => "challenge",
            FallbackReason::JsApp => "js_app",
            FallbackReason::NoActions => "no_actions",
            FallbackReason::Forced => "forced",
        }
    }
}

/// Markers of anti-bot interstitials. Deliberately specific strings: pages
/// merely *mentioning* captchas are rare, while real walls embed these
/// ids/classes verbatim (reCAPTCHA, hCaptcha, Cloudflare Turnstile/challenge).
const CHALLENGE_MARKERS: &[&str] = &[
    "g-recaptcha",
    "h-captcha",
    "cf-turnstile",
    "cf-chl-",
    "challenge-form",
    "challenge-platform",
    "_cf_chl_opt",
];

/// "Complex UI" markers that behave like a JS app for extraction purposes:
/// content drawn into a canvas or mounted behind shadow roots is invisible to
/// the HTTP-only pipeline.
const COMPLEX_UI_MARKERS: &[&str] = &["<canvas", "attachShadow"];

/// Decide whether a settled snapshot warrants ONE headless-Chrome escalation.
/// Pure — looks only at the distilled snapshot and the raw fetched HTML; never
/// fetches or renders anything itself.
pub fn assess(snapshot: &Distilled, raw_html: &str) -> Option<FallbackReason> {
    if CHALLENGE_MARKERS.iter().any(|m| raw_html.contains(m)) {
        return Some(FallbackReason::Challenge);
    }

    let thin = snapshot.diagnostics.as_ref().is_some_and(|d| d.low_content)
        || visible_chars(&snapshot.text) < render::JS_TEXT_THRESHOLD;
    let js_shell = render::looks_like_js_app(raw_html)
        || COMPLEX_UI_MARKERS.iter().any(|m| raw_html.contains(m));

    // An unrendered SPA shell: scripts present, almost no extractable content.
    if thin && js_shell {
        return Some(FallbackReason::JsApp);
    }

    // Browser-Use signal: actions were requested and none were found while the
    // page clearly runs scripts — the operable surface is built client-side.
    if snapshot.actions.as_ref().is_some_and(|a| a.is_empty()) && js_shell {
        return Some(FallbackReason::NoActions);
    }

    None
}

fn visible_chars(text: &str) -> usize {
    text.split_whitespace().map(str::len).sum()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{DistillOptions, Profile, distill_html};

    fn snap(html: &str, actions: bool) -> Distilled {
        distill_html(
            html,
            "https://e.com/",
            &DistillOptions {
                profile: Profile::Full,
                extract_actions: actions,
                diagnostics: true,
                ..Default::default()
            },
        )
        .unwrap()
    }

    /// A text-rich static page (no scripts) with real links.
    fn article() -> String {
        format!(
            "<html><body><article><h1>Title</h1><p>{}</p>\
             <a href=\"/next\">Next chapter</a></article></body></html>",
            "Plenty of real readable content. ".repeat(20)
        )
    }

    #[test]
    fn challenge_markers_escalate_first() {
        let html = r#"<html><body><form class="challenge-form" id="challenge-form">
            <div class="g-recaptcha"></div></form></body></html>"#;
        let s = snap(html, true);
        assert_eq!(assess(&s, html), Some(FallbackReason::Challenge));
    }

    #[test]
    fn unrendered_spa_shell_is_js_app() {
        let html = r#"<html><head><script src="/bundle.js"></script>
            <script>window.boot=1</script></head>
            <body><div id="root"></div></body></html>"#;
        let s = snap(html, true);
        assert_eq!(assess(&s, html), Some(FallbackReason::JsApp));
    }

    #[test]
    fn canvas_only_page_counts_as_js_app() {
        let html = r#"<html><body><canvas id="stage"></canvas></body></html>"#;
        let s = snap(html, false);
        assert_eq!(assess(&s, html), Some(FallbackReason::JsApp));
    }

    #[test]
    fn rich_static_article_stays_rb_only() {
        let html = article();
        let s = snap(&html, true);
        assert_eq!(assess(&s, &html), None);
    }

    #[test]
    fn scripty_page_with_zero_actions_escalates() {
        // Enough text that it is not "thin", but ZERO operable actions while
        // scripts are clearly present → the action surface is JS-built.
        let html = format!(
            "<html><head><script src=\"/a.js\"></script><script>let x=1</script></head>\
             <body><p>{}</p></body></html>",
            "Readable prose without any links or forms at all. ".repeat(20)
        );
        let s = snap(&html, true);
        assert_eq!(assess(&s, &html), Some(FallbackReason::NoActions));
    }

    #[test]
    fn static_text_page_without_actions_stays() {
        // No scripts: an action-less static page is just a page, not a JS app.
        let html = format!(
            "<html><body><p>{}</p></body></html>",
            "Static text with nothing operable on it. ".repeat(20)
        );
        let s = snap(&html, true);
        assert_eq!(assess(&s, &html), None);
    }
}
